### ISSUE TITLE
Generate mz image with list of ions

### ISSUE THREAD

**Issue by educhicano** [foellmelanie/docker-galaxy-msi#1]
Hi Melanie!
First of all, let me congrats you for this job. It's no easy to pack a MSI analysis like you are doing with Galaxy/Docker... You are really making the analysis very accesible to unexperienced users. Well done!!!
I'm a newbie in this kind of containers, so i dont know that this is a problem of dependencies or a problem generated by my files. 
When i try to represent 3 different ions in my analyze7.5 file the galaxy dialog gives me this:

error
An error occurred with this dataset:
library(Cardinal)
library(gridExtra)
library(lattice)
        loadRData <- function(fileName){
        load(fileName)
        get(ls()[ls() != "fileName"])
        }
            msidata = loadRData('infile.RData')
   maxfeatures = length

I dont know what is wrong. In my case I've loaded img, hdr and t2m files in the environment (do i need all of them?) and if i check via admin, it seems to have all dependencies installed. Any suggestion?
Regards!

**Comment by foellmelanie** [comment]
Hi, 
happy to hear that you like it. 
The docker container automatically installs all dependencies. I assume that the upload of the files was not correct, all three Analyze 7.5 files need to be uploaded via the "composite" function of Galaxy. You can checkout the tutorial that describes both, the file upload and how to generate an overlay image: [https://galaxyproject.github.io/training-material/topics/metabolomics/tutorials/msi-analyte-distribution/tutorial.html](https://galaxyproject.github.io/training-material/topics/metabolomics/tutorials/msi-analyte-distribution/tutorial.html). If the error persists, please let me know. You can find more tutorials in the proteomics and metabolomics [Galaxy training material](https://galaxyproject.github.io/training-material/).
You could also use the [European Galaxy server](https://usegalaxy.eu) and send a full error report with all parameters what makes trouble shooting easier for me. 
Best,
Melanie

**Comment by educhicano** [comment]
Hi! Sorry for the delay, but we had many jobs pending these days at our lab...
I've used both systems, usegalaxy.eu and locally and now i can load my files but it only works in both systems with imzML files. It doesnt really worry me because i can convert analyze7.5 to imzML but it seems that composite function is not working properly because the error is the same. It seems that with analyze7.5 cardinal doesnt work.
Thanks again for your time and effort to give MSI community a unvaluable tool like this.

**Comment by foellmelanie** [comment]
No worries about the delay, it is the same here. I am happy if everything worked fine for imzML files.

**Comment by foellmelanie** [comment]
If you have further problems, just let me know.
